backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/static/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Sitewide Options"
    name: "options"
    editor:
      preview: false
    files:
      - label: "Main Menu"
        name: "nav"
        file: "/data/nav.yml"
        fields:
          - label: "Menu Items"
            label_singular: "Menu Item"
            name: "topLevelItems"
            widget: "list"
            hint: "Change default menu items."
            fields:
              - {label: Display Text, name: displayText, widget: string, hint: 'Enter the name of the page that will be linked in the menu.', required: true}
              - label: "Select Page"
                required: true
                name: "selectPage"
                widget: "relation"
                collection: "pages"
                search_fields: ["name"]
                value_field: "name"
                display_fields: ["name"]
                hint: "Select the page from the main pages collection."
              - label: "Item Type"
                required: true
                name: "itemType"
                widget: "select"
                options: ["Link", "Button"]
                hint: "Choose the display option for menu link."
          - label: "Custom Page Menu Items"
            label_singular: "Custom Page Menu Item"
            name: "customItems"
            widget: "list"
            hint: "Add custom pages to the menu."
            fields:
              - {label: Display Text, name: displayText, widget: string, hint: 'Enter the name of the page that will be linked in the menu.', required: true}
              - label: "Select Page"
                required: true
                name: "selectPage"
                widget: "relation"
                collection: "custom_page"
                search_fields: ["title"]
                value_field: "title"
                display_fields: ["name"]
                hint: "Select the page from the custom pages collection."
              - label: "Item Type"
                required: true
                name: "itemType"
                widget: "select"
                options: ["Link", "Button"]
                hint: "Choose the display option for menu link."
          - label: "Social Media Menu Items"
            label_singular: "Social Media Menu Item"
            name: "socialItems"
            widget: "list"
            hint: "Add social media links to the menu."
            fields:
              - label: "Social Media Account URL"
                required: true
                name: "socialURL"
                widget: "string"
                hint: "Paste a link to the WWF social media account"
              - label: "Social Media Icon"
                required: true
                name: "socialIcon"
                widget: "image"
                hint: "Theme-styled icons are available in the media gallery or can be uploaded here."

      - label: "Site Logo"
        name: "logo"
        editor:
          preview: true
        file: "/data/logo.yml"
        widget: "image"
        fields:
          - {label: Logo, name: logo, widget: image, hint: WARNING - Adding an image here will override the default dynamically filled SVG. See 'Logo' section in 'Site Help' for more information.}
  - label: "Pages"
    name: "pages"
    editor:
      preview: true
    files:
      - label: "Home"
        name: "home"
        file: "/content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Project Index"
        name: "project_index"
        file: "/content/project_index/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Project Gallery"
        name: "project_gallery"
        file: "/content/project_gallery/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "About"
        name: "about"
        file: "/content/about/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Contact"
        name: "contact"
        file: "/content/contact/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: "Location", name: "location", widget: "map" }
  - name: 'custom_page'
    label: 'Custom Page'
    folder: 'content/custom_page'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'project'
    label: 'Project'
    folder: 'content/project'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Artist', name: 'artist', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - { label: 'Material', name: 'material', widget: 'string' }
      - { label: 'Attribution', name: 'attribution', widget: 'string' }
      - { label: 'Featured Image', name: '1_image', widget: 'image' }
      - label: "Thumbnails"
        name: "thumbnailImages"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
