backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/static/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Sitewide Options"
    name: "options"
    editor:
      preview: false
    files:
      - label: "Main Menu"
        name: "nav"
        file: "/data/nav.yml"
        fields:
          - label: "Menu Items"
            label_singular: "Menu Item"
            name: "topLevelItems"
            widget: "list"
            hint: "Change default menu items."
            fields:
              - {label: Display Text, name: displayText, widget: string, hint: 'Enter the name of the page that will be linked in the menu.', required: true}
              - label: "Select Page"
                name: "selectPage"
                widget: "relation"
                collection: "pages"
                search_fields: ["title"]
                value_field: "url"
                display_fields: ["title"]
                hint: "Select the page from the main pages collection."
              - label: "Item Type"
                name: "itemType"
                widget: "select"
                options: ["Link", "Button"]
                hint: "Choose the display option for menu link."
          - label: "Custom Page Menu Items"
            label_singular: "Custom Page Menu Item"
            name: "customItems"
            widget: "list"
            hint: "Add custom pages to the menu."
            fields:
              - {label: Display Text, name: displayText, widget: string, hint: 'Enter the name of the page that will be linked in the menu.', required: true}
              - label: "Select Page"
                name: "selectPage"
                widget: "relation"
                collection: "custom_page"
                search_fields: ["title"]
                value_field: "title"
                display_fields: ["name"]
                hint: "Select the page from the custom pages collection."
              - label: "Item Type"
                name: "itemType"
                widget: "select"
                options: ["Link", "Button"]
                hint: "Choose the display option for menu link."
          - label: "Social Media Menu Items"
            label_singular: "Social Media Menu Item"
            name: "socialItems"
            widget: "list"
            hint: "Add social media links to the menu."
            fields:
              - label: "Social Media Account URL"
                name: "socialURL"
                widget: "string"
                hint: "Paste a link to the WWF social media account"
              - label: "Social Media Icon"
                name: "socialIcon"
                widget: "image"
                hint: "Theme-styled icons are available in the media gallery or can be uploaded here."
      - label: "Site Logo"
        name: "logo"
        editor:
          preview: false
        file: "/data/logo.yml"
        fields:
          - label: "SVG Logo Editor"
            required: true
            name: "svgEditor"
            widget: "code"
            allow_language_selection: false
            default_language: "html"
            hint: "WARNING - SVG snippets entered here will ovewrite the current logo. Please only insert valid SVG logo snippets. Learn more about SVG in the site help section."
      - label: "Site Description"
        name: "meta"
        editor:
          preview: false
        file: "/data/meta.yml"
        fields:
          - label: "Site Description"
            name: "description"
            required: true
            widget: "text"
            hint: "The site 'meta' description is available on every page. Search engines often use the description in search results to preview the site's content briefly."
      - label: "Config"
        name: "config"
        editor:
          preview: false
        file: "/config.toml"
        fields:
          - label: "Site Base URL"
            name: "baseURL"
            required: true
            widget: "hidden"
            default: "/"
          - label: "Title"
            name: "title"
            required: true
            widget: "string"
      - label: "Site Footer"
        name: "footer"
        editor:
          preview: false
        file: "/layout/partials/footer.html"
        fields:
          - label: "Site Footer"
            label_singular: "Site Footer Item"
            required: true
            name: "footer"
            widget: "list"
            hint: "Change site-wide footer."
            fields:
                - label: "Placeholder"
                  name: "placeholder"
                  widget: "string"
  - label: "Pages"
    name: "pages"
    editor:
      preview: true
    files:
      - label: "Home"
        name: "home"
        file: "/content/_index.md"
        fields:
          - label: 'Video Reel'
            name: 'reelVideo'
            widget: 'list'
            fields:
              - label: 'Video'
                name: 'video'
                widget: 'file'
      - label: "Project Index"
        name: "project_index"
        file: "/content/index/_index.md"
        fields:
          - {label: 'URL', name: 'url', widget: 'string', default: 'projects' }
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Intro', name: 'intro', widget: 'markdown'}
      - label: "Project Gallery"
        name: "project_gallery"
        file: "/content/gallery/_index.md"
        fields:
          - {label: 'URL', name: 'url', widget: 'string', default: 'gallery' }
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Intro', name: 'intro', widget: 'markdown'}
      - label: "About"
        name: "about"
        file: "/content/about/_index.md"
        fields:
          - {label: 'URL', name: 'url', widget: 'string', default: 'about' }
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Intro', name: 'intro', widget: 'markdown'}
      - label: "Contact"
        name: "contact"
        file: "/content/contact/_index.md"
        fields:
          - {label: 'URL', name: 'url', widget: 'string', default: 'contact' }
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Intro', name: 'intro', widget: 'markdown'}
          - {label: "Location", name: "location", widget: "map" }
  - name: 'custom_page'
    label: 'Custom Page'
    folder: 'content/custom_page'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - label: "Page Title"
        name: "title"
        required: true
        widget: "string"
      - label: "URL Slug"
        name: "url"
        required: true
        widget: "string"
      - label: "Sections"
        label_singular: "Section"
        name: "sections"
        widget: "list"
        required: false
        types:
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - label: "Select Header Justfication"
                name: "sectionLayout"
                widget: "select"
                options:
                  - { label: "Left Justified", value: "Left" }
                  - { label: "Center Justified", value: "Center" }
                  - { label: "Right Justified", value: "Right" }
              - label: "Header Text"
                name: "headerText"
                widget: "markdown"
          - label: "Image"
            name: "imageBlock"
            widget: "object"
            fields:
              - label: "Select Image Justfication"
                name: "imageLayout"
                widget: "select"
                options:
                  - { label: "Left Justified", value: "Left" }
                  - { label: "Center Justified", value: "Center" }
                  - { label: "Right Justified", value: "Right" }
              - label: "Image"
                name: "image"
                widget: "image"
          - label: "Text Block"
            label_singular: "text"
            name: "textBlock"
            widget: "object"
            fields:
              - label: "Select Text Block Justfication"
                name: "textJustification"
                widget: "select"
                options:
                  - { label: "Left Justified", value: "Left" }
                  - { label: "Center Justified", value: "Center" }
                  - { label: "Right Justified", value: "Right" }
              - label: "Text"
                name: "text"
                widget: "markdown"
          - label: "Tile Gallery"
            name: "tileGallery"
            widget: "object"
            fields:
              - label: "Custom Tile Gallery"
                label_singular: "Image"
                name: "tileGalleryCustom"
                widget: "list"
                summary: '{{fields.image}}'
                field: {label: Image, name: image, widget: image}
          - label: "Carousel Gallery"
            label_singular: "Image"
            name: "carouselGallery"
            widget: "object"
            fields:
              - label: "Custom Carousel Gallery"
                name: "carouseleGalleryCustom"
                widget: "list"
                summary: '{{fields.image}}'
                field: {label: Image, name: image, widget: image}
  - label: 'Project'
    name: 'project'
    folder: 'content/project'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Artist', name: 'artist', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - { label: 'Material', name: 'material', widget: 'string' }
      - { label: 'Attribution', name: 'attribution', widget: 'string' }
      - { label: 'Featured Image', name: '1_image', widget: 'image' }
      - label: "Thumbnails"
        name: "thumbnailImages"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
