backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/static/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Sitewide Options"
    name: "options"
    editor:
      preview: false
    files:
      - label: "Main Menu"
        name: "nav"
        file: "_data/nav.yml"
        fields:
          - label: "Menu Items"
            label_singular: "Menu Item"
            name: "topLevelItems"
            widget: "list"
            fields:
              - {label: Display Text, name: displayText, widget: string}
              - {label: URL, name: url, widget: string}
              - label: "Item Type"
                name: "itemType"
                widget: "select"
                options: ["Link", "Button"]
          - label: "Header"
            name: "header"
            fields:
              - {label: Logo, name: logo, widget: image}
              - {label: URL, name: url, widget: string}
  - label: "Pages"
    name: "pages"
    editor:
      preview: true
    files:
      - label: "Home"
        name: "home"
        file: "/content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Project Index"
        name: "project_index"
        file: "/content/project_index/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Project Gallery"
        name: "project_gallery"
        file: "/content/project_gallery/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "About"
        name: "about"
        file: "/content/about/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Contact"
        name: "contact"
        file: "/content/contact/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
  - name: 'custom_page'
    label: 'Custom Page'
    folder: 'content/custom_page'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'project'
    label: 'Project'
    folder: 'content/project'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Artist', name: 'artist', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - { label: 'Material', name: 'material', widget: 'string' }
      - { label: 'Attribution', name: 'attribution', widget: 'string' }
      - { label: 'Featured Image', name: '1_image', widget: 'image' }
      - label: "Thumbnails"
        name: "thumbnailImages"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
