backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "/content/uploads/images"
public_folder: "/uploads/images"
collections:
  - label: "Sitewide Options"
    name: "options"
    editor:
      preview: false
    files:
      - label: "Main Menu"
        name: "nav"
        file: "/data/nav.yml"
        fields:
          - label: "Menu Items"
            label_singular: "Menu Item"
            name: "topLevelItems"
            widget: "list"
            hint: "Change default menu items."
            fields:
              - {label: Display Text, name: displayText, widget: string, hint: 'Enter the name of the page that will be linked in the menu.', required: true}
              - label: "Select Page"
                name: "selectPage"
                widget: "relation"
                collection: "pages"
                search_fields: ["title"]
                value_field: "url"
                display_fields: ["title"]
                hint: "Select the page from the main pages collection."
              - label: "Item Type"
                name: "itemType"
                widget: "select"
                options: ["Link", "Button"]
                hint: "Choose the display option for menu link."
          - label: "Custom Page Menu Items"
            label_singular: "Custom Page Menu Item"
            name: "customItems"
            widget: "list"
            hint: "Add custom pages to the menu."
            fields:
              - {label: Display Text, name: displayText, widget: string, hint: 'Enter the name of the page that will be linked in the menu.', required: true}
              - label: "Select Page"
                name: "selectPage"
                widget: "relation"
                collection: "custom_page"
                search_fields: ["title"]
                value_field: "url"
                display_fields: ["title"]
                hint: "Select the page from the custom pages collection."
              - label: "Item Type"
                name: "itemType"
                widget: "select"
                options: ["Link", "Button"]
                hint: "Choose the display option for menu link."
          - label: "Social Media Menu Items"
            label_singular: "Social Media Menu Item"
            name: "socialItems"
            widget: "list"
            hint: "Add social media links to the menu."
            fields:
              - label: "Social Media Account URL"
                name: "socialURL"
                widget: "string"
                hint: "Paste a link to the WWF social media account"
              - label: "Social Media Icon"
                name: "socialIcon"
                widget: "image"
                hint: "Theme-styled icons are available in the media gallery or can be uploaded here."
      - label: "Site Logo"
        name: "logo"
        editor:
          preview: false
        file: "/data/logo.yml"
        fields:
          - label: "SVG Logo Editor"
            required: true
            name: "svgEditor"
            widget: "code"
            allow_language_selection: false
            default_language: "html"
            hint: "WARNING - SVG snippets entered here will ovewrite the current logo. Please only insert valid SVG logo snippets. Learn more about SVG in the site help section."
      - label: "Site Description"
        name: "meta"
        editor:
          preview: false
        file: "/data/meta.yml"
        fields:
          - label: "Site Description"
            name: "description"
            required: true
            widget: "text"
            hint: "The site 'meta' description is available on every page. Search engines often use the description in search results to preview the site's content briefly."
      - label: "Site Title"
        name: "config"
        editor:
          preview: false
        file: "/config.toml"
        fields:
          - label: "Site Base URL"
            name: "baseURL"
            required: true
            widget: "hidden"
            default: "/"
          - label: "Site Name"
            name: "title"
            required: true
            widget: "string"
      - label: "Contact Information"
        name: "contact"
        editor:
          preview: false
        file: "/data/contact.yml"
        fields:
          - label: "Address Line One"
            name: "addressOne"
            widget: "text"
          - label: "Address Line Two"
            name: "addressTwo"
            widget: "text"
          - label: "Phone Number"
            name: "phone"
            widget: "string"
          - label: "Info Email"
            name: "email"
            widget: "string"
      - label: "Project Filter Tags"
        name: "filter_tags"
        editor:
          preview: false
        file: "/data/tags.yml"
        fields:
          - label: "Material Tags"
            label_singular: "Material Tag"
            name: "material_tag"
            widget: "list"
            hint: "WARNING - Tags should be one word only."
            fields:
              - {label: 'Tag', name: 'material_string', widget: 'string'}
          - label: "Process Tags"
            label_singular: "Process Tag"
            name: "process_tag"
            widget: "list"
            hint: "WARNING - Tags should be one word only."
            fields:
              - {label: 'Tag', name: 'process_string', widget: 'string'}
          - label: "Year Tags"
            label_singular: "Year Tag"
            name: "year_tag"
            widget: "list"
            hint: "WARNING - Tags should be one word only."
            fields:
              - {label: 'Tag', name: 'year_string', widget: 'string'}
  - label: "Pages"
    name: "pages"
    editor:
      preview: true
    files:
      - label: "Home"
        name: "home"
        file: "/content/_index.md"
        fields:
          - label: 'Video Reel'
            name: 'reelVideo'
            widget: 'list'
            fields:
              - label: 'Video'
                name: 'video'
                widget: 'file'
      - label: "Project Index"
        name: "project_index"
        file: "/content/project_index/_index.md"
        fields:
          - {label: 'URL Slug', name: 'url', widget: 'hidden', default: 'project_index'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Intro', name: 'intro', widget: 'markdown'}
      - label: "About"
        name: "about"
        file: "/content/about/_index.md"
        path: 'about/index'
        fields:
          - {label: 'URL Slug', name: 'url', widget: 'hidden', default: 'about'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Subtitle', name: 'subtitle', widget: 'string'}
          - label: 'Hero Banner'
            name: 'hero_obj'
            widget: 'object'
            fields:
              - label: 'Hero Image'
                name: 'hero'
                widget: 'image'
              - label: 'Alt Text'
                name: 'alt'
                widget: 'string'
          - {label: 'Statement', name: 'statement', widget: 'markdown'}
          - label: 'Archived Projects'
            label_singular: 'Archive Project'
            name: 'archive'
            widget: 'list'
            fields: 
              - label: 'Archive Entries'
                label_singular: 'Archive Entry'
                name: 'archive_obj'
                widget: 'object'
                fields:
                  - label: 'Archive Image'
                    name: 'archive_image'
                    widget: 'image'
                  - label: 'Title'
                    name: 'archive_title'
                    widget: 'string'
                  - label: 'Artist'
                    name: 'archive_artist'
                    widget: 'string'
                  - label: 'Year'
                    name: 'archive_year'
                    widget: 'string'
          - {label: 'Intro', name: 'intro', widget: 'markdown'}
      - label: "Contact"
        name: "contact"
        file: "/content/contact/_index.md"
        media_folder: '/content/contact/images/'
        public_folder: '/contact/images/'
        path: 'contact/index'
        fields:
          - {label: 'URL Slug', name: 'url', widget: 'hidden', default: 'contact'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Intro', name: 'intro', widget: 'markdown'}
          - label: 'Locations'
            label_singular: 'Location'
            name: 'locations'
            widget: 'list'
            fields:
              - label: 'Location Name'
                name: 'location_name'
                widget: 'string'
              - label: 'Location Address'
                name: 'location_address'
                widget: 'text'
              - label: 'Coordinates'
                name: 'coordinates'
                widget: 'map'
  - name: 'custom_page'
    label: 'Custom Page'
    folder: 'content/custom_page'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - label: "Page Title"
        name: "title"
        required: true
        widget: "string"
      - label: "URL Slug"
        name: "url"
        required: true
        widget: "string"
      - label: "Sections"
        label_singular: "Section"
        name: "sections"
        widget: "list"
        required: false
        types:
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - label: "Select Header Justfication"
                name: "sectionLayout"
                widget: "select"
                options:
                  - { label: "Left Justified", value: "Left" }
                  - { label: "Center Justified", value: "Center" }
                  - { label: "Right Justified", value: "Right" }
              - label: "Header Text"
                name: "headerText"
                widget: "markdown"
          - label: "Image"
            name: "imageBlock"
            widget: "object"
            fields:
              - label: "Select Image Justfication"
                name: "imageLayout"
                widget: "select"
                options:
                  - { label: "Left Justified", value: "Left" }
                  - { label: "Center Justified", value: "Center" }
                  - { label: "Right Justified", value: "Right" }
              - label: "Image"
                name: "image"
                widget: "image"
          - label: "Text Block"
            label_singular: "text"
            name: "textBlock"
            widget: "object"
            fields:
              - label: "Select Text Block Justfication"
                name: "textJustification"
                widget: "select"
                options:
                  - { label: "Left Justified", value: "Left" }
                  - { label: "Center Justified", value: "Center" }
                  - { label: "Right Justified", value: "Right" }
              - label: "Text"
                name: "text"
                widget: "markdown"
          - label: "Tile Gallery"
            name: "tileGallery"
            widget: "object"
            fields:
              - label: "Custom Tile Gallery"
                label_singular: "Image"
                name: "tileGalleryCustom"
                widget: "list"
                summary: '{{fields.image}}'
                field: {label: Image, name: image, widget: image}
          - label: "Carousel Gallery"
            label_singular: "Image"
            name: "carouselGallery"
            widget: "object"
            fields:
              - label: "Custom Carousel Gallery"
                name: "carouseleGalleryCustom"
                widget: "list"
                summary: '{{fields.image}}'
                field: {label: Image, name: image, widget: image}
  - label: 'Projects'
    label_singular: 'Project'
    name: 'projects'
    folder: 'content/projects'
    media_folder: '/content/projects/{{title}}/images/'
    public_folder: '/projects/{{title}}/images/'
    path: '{{title}}/index'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Artist', name: 'artist', widget: 'string' }
      - label: "Year"
        label_singular: "Year"
        name: "year_tag"
        widget: "relation"
        collection: "options"
        file: "filter_tags"
        multiple: false
        search_fields: ["year_tag.*.year_string"]
        display_fields: ["year_tag.*.year_string"]
        value_field: "year_tag.*.year_string"
      - { label: 'Material', name: 'material', widget: 'string' }
      - label: 'Attribution'
        name: 'attribution'
        widget: 'string'
        required: false
      - { label: 'Featured Image', name: 'featured', widget: 'file' }
      - label: "Thumbnails"
        name: "thumbnailImages"
        widget: "list"
        summary: '{{fields.image}}'
        fields:
          - label: 'Thumbnail Images'
            label_singular: 'Thumbnail Image'
            name: 'image'
            widget: 'file'
      - label: "Material Tags"
        label_singular: "Material Tag"
        name: "material_tag"
        widget: "relation"
        collection: "options"
        file: "filter_tags"
        multiple: true
        search_fields: ["material_tag.*.material_string"]
        display_fields: ["material_tag.*.material_string"]
        value_field: "material_tag.*.material_string"
      - label: "Process Tags"
        label_singular: "Process Tag"
        name: "process_tag"
        widget: "relation"
        collection: "options"
        file: "filter_tags"
        multiple: true
        search_fields: ["process_tag.*.process_string"]
        display_fields: ["process_tag.*.process_string"]
        value_field: "process_tag.*.process_string"

